# 设置端口号
server:
  port: 8082

# 数据库相关配置
spring:
  datasource:
    url: jdbc:mysql://47.101.223.181:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: wyc
    password: wycfight666

# Mybatis相关配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:top/**/mapper/*.xml

# 日志相关配置
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug

# Swagger界面内容配置
swagger:
  title: Thank API接口文档
  description: good good study, day day up!
  version: 1.0.0
  termsOfServiceUrl: http://wycfight.top
  contact:
    name: Shop
    url: http://wycfight.top
    email: wycfight@163.com