# 数据库连接池druid配置
spring:
  datasource:
    url: jdbc:mysql://47.101.223.181:3306/shop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: wyc
    password: wycfight666
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
# elasticsearch 配置 enabled 默认为true 开启 Elasticsearch 仓库
# cluster-nodes 集群节点地址列表，用逗号分隔。如果没有指定，就启动一个客户端节点。
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 47.101.223.181:9300
logging:
  path: /var/logs # 配置日志生成目录