spring:
  profiles:
    active: dev #默认为开发环境

server:
  port: 8081

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:top/**/mapper/*.xml

logging:
  level:
    root: info
    top.wycfight.shop: debug